### ISSUE TITLE
Nothing to show

### ISSUE THREAD

**Issue by Twelve57** [hoffmanjon/SQLiteDataAccessLayer2#1]
Hi, it's me or there is nothing in your demo project ?
It's just an empty project to me...

**Comment by hoffmanjon** [comment]
The project looks good to me.   How are you downloading it

**Comment by Twelve57** [comment]
By zip
But, I found the example project at : https://github.com/hoffmanjon/SQLiteDataAccessLayer

It's ok now,
thanks for your time.

Regards ;)

**Comment by andrecsa** [comment]
Hi @hoffmanjon 
I've also downloaded the ZIP and looks like the project is empty.

When I try to create a project from scratch, adding the SQLite framework to the Linked Frameworks and Libraries, I get an error saying that the framework hasn't been found. See screenshot below.
![screen shot 2015-11-17 at 9 33 49 pm](https://cloud.githubusercontent.com/assets/15334159/11210290/f03f0750-8d72-11e5-83a7-3cfec7a4bdc2.png)

Any idea how to fix it?

Thanks.

**Comment by Twelve57** [comment]
Did you try to download this project ?
https://github.com/hoffmanjon/SQLiteDataAccessLayer

Or did you try to add it with cocoapods ?

**Comment by django-emerge** [comment]
I'm not seeing the source code in this project when I download it either (both via zip and clone).  Browsing the source up here on github shows no real custom code either (just looks like a new xcode project).

I've downloaded the other repository mentioned in previous comments (https://github.com/hoffmanjon/SQLiteDataAccessLayer), but this is not Swift 2 syntax, which is what I'm after.  Error type files, etc.

Thanks for this btw, it was just what I was looking for.

**Comment by Twelve57** [comment]
I think you can write swift2 code with SQLiteDataAccessLayer.
If you just want to handle error, I can give you some example.

From my own code, I write a DAO for a "simple" example object : 

static func containsId(item: T) throws -> Bool {
        guard let DB = SQLiteDataStore.instance.BBDB else {
            throw SQLiteDataStore.DataAccessError.Datastore_ConnectionError
        }
        let query = table.filter(simpleId == item.id!)
        let items = DB.prepare(query)
        for _ in items {
            print("Contains")
            return true
        }
        print("Not Contains")
        return false
    }
    
    static func insert(item: T) throws -> Void {
        guard let DB = SQLiteDataStore.instance.BBDB else {
            throw SQLiteDataStore.DataAccessError.Datastore_ConnectionError
        }
        do {
            let insert = table.insert(simpleId <- item.id!, simpleName <- item.name!, simpleNumber <- item.number!)
            _ = try DB.run(insert)
        } catch {
            throw SQLiteDataStore.DataAccessError.Insert_Error
        }
    }

I'm using do try catch and throw to handle error/exception.
I hope i was helping ;)

**Comment by hoffmanjon** [comment]
I will take a look at it this weekend to see why the files are missing.  Sorry for the delay in response, normally I respond a lot quicker but I have been pulled on other things this week and have not had a chance to look at my personal projects.  I really apologize for the delay.

**Comment by django-emerge** [comment]
Thanks for the responses.

I triangulated most of what I needed from the blog post and the other repo.  However, the full example would probably be nice for posterity...

**Comment by hoffmanjon** [comment]
I updated the code and all of the files should be there.  Really is not much to the project, it just prints results to the console as shown in the blog post.  Don't forget to add SQLite.Swift to the project once you download it.
